# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update;brew install libgit2; fi

os:
  - linux
  - osx

r:
  - oldrel
  - release
  - devel

after_success:
  - Rscript -e 'covr::codecov()'
