# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

os:
  - linux
  - osx

r:
  - oldrel
  - release

include:
  matrix:
    - name: "devel linux"
      language: R
      r: devel
      os: linux
    - name: "devel osx"
      language: R
      r: devel
      os: osx
      warnings_are_errors: false

after_success:
  - Rscript -e 'covr::codecov()'
